<%@ Page Language="C#" MasterPageFile="~/COPaKB.master" AutoEventWireup="true" CodeFile="COPaTools.aspx.cs" Inherits="COPaTools" Title="Cardiac Organellar Protein Atlas Knowledgebase (COPaKB) —— Proteomics Tools" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

<div class="row-fluid">
    <h2>Bioinformatics Tools for Cardiac Proteome Biology </h2>
</div>
<div class="row-fluid">
    <div class="span12">
        <h4>COPaKB Related Tools</h4>
    </div>
    <div class="span12">
        <div class="row-fluid">
            <div class="span12">
                <ul>
                    <li><a href="COPaKBClient.aspx" target="_blank">COPaKB Client</a> is a versatile tool that allows you to process and analyze a large batch of raw proteomic datasets. Its latest version (V2.0) was built in Java; therefore, it functions in Windows, OS X (Mac) or Linux with Java 7 environment. COPaKB Client provides an integrated hub for task management, file management, data transfer and result display. The program thus provides a reliable access to COPaKB via robust web services.</li>
                    <li><a href="https://itunes.apple.com/us/app/icopa/id568723410?mt=8" target="_blank">iCOPa</a> is the very first mobile App created for proteomic analyses. The latest version (V2.1) is available for download from the Apple's App store, and it functions on iPad devices with iOS 5 or 6 operating system. You can access COPaKB via iCOPa if there is available network connection.</li>
                    <li><a href="http://proteowizard.sourceforge.net/" target="_blank">ProteoWizard Converter </a> is an open source application developed by <a href="http://proteowizard.sourceforge.net/project.shtml">the ProteoWizard Software Foundation</a>. This application converts raw mass spectral files into mzML format, the standard XML format established by <a href="http://www.psidev.info/mzml">PSI</a>. COPaKB Client has an option to streamline the processes of file converstion and analysis by utilzing ProteoWizard Converter.</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <h4>Resources from EBI</h4>
    </div>
    <div class="span12">
        <div class="row-fluid">
            <div class="span12">
                <ul>
                    <li><a href="http://www.expasy.org/tools/aldente">ProteomeXchange</a> - The mission of the ProteomeXchange consortium, as stated in its website, is to "provide a coordinated submission of MS/MS proteomics data to the main existing proteomics repositories, and to encourage optimal data dissemination."</li>
                    <li><a href="http://www.ebi.ac.uk/pride/" target="_blank">PRIDE</a> - The PRIDE (PRoteomics IDEntifications) database, according to its website, is "a centralized, standards compliant, public data repository for proteomics data, including protein and peptide identifications, post-translational modifications and supporting spectral evidence." </li>
                    <li><a href="http://www.ebi.ac.uk/intact/" target="_blank">IntAct</a> - IntAct, according to its website, "provides a freely available, open source database system and analysis tools for molecular interaction data. All interactions are derived from literature curation or direct user submissions and are freely available." </li>
                    <li><a href="http://www.uniprot.org/" target="_blank">UniProt</a> - The mission of UniProt, according to its website, is to "provide the scientific community with a comprehensive, high-quality and freely accessible resource of protein sequence and functional information." </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <h4>Resources from KTH</h4>
    </div>
    <div class="span12">
        <div class="row-fluid">
            <div class="span12">
                <ul>
                    <li><a href="http://www.proteinatlas.org/" target="_blank">HPA</a> - The HPA (Human Protein Atlas), according to its website, is "a publicly available database with millions of high-resolution images showing the spatial distribution of proteins in 46 different normal human tissues and 20 different cancer types, as well as 47 different human cell lines." </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <h4>Resources from TSRI</h4>
    </div>
    <div class="span12">
        <div class="row-fluid">
            <div class="span12">
                <ul>
                    <li><a href="http://fields.scripps.edu/downloads.php" target="_blank">RawExtractor</a> - RawExtractor is a program to extract MS and MS/MS spectra from RAW files generated by Thermo mass spectrometers, such as LCQ, LTQ and LTQ-Orbitrap. Extracted spectra data are saved in ms1, ms2 or mzXML formats.</li>
                    <li><a href="http://en.wikipedia.org/wiki/SEQUEST‎" target="_blank">SEQUEST</a> - SEQUEST performs protein identification and peptide sequencing by comparing fragmentation patterns of mass spectral datasets with those of theoretical mass spectral datasets derived from protein or nucleotide databases.</li>  
                    <li><a href="http://fields.scripps.edu/downloads.php" target="_blank">ProLuCID</a> - ProLuCID, according to TSRI website, is "a fast and sensitive tandem mass spectra-based protein identification algorithm."</li>   
                    <li><a href="http://fields.scripps.edu/downloads.php" target="_blank">DTASelect</a> - DTASelect organizes and filters the results of SEQUEST/ProLuCID analyses. The output for the protein identification process will meet a pre-set threshold value for false discovery rate.</li>  
                    <li><a href="http://fields.scripps.edu/census/index.php" target="_blank">Census</a> - Census supports quantitative analysis of individual proteins in mass spectrometry-based proteomic datasets. It can be used for both stable isotope labeling and label-free studies.</li>
                </ul>
            </div>
        </div>
    </div>
</div>
</asp:Content>

